# WebServer Default Configuration File
# Based on NGINX configuration style

# -------- SERVER 1 --------
# Main website
server {

    server_name localhost;

    listen 127.0.0.1:8080;

    client_max_body_size 10M;

    root ./;

    error_page 400 /error/400.html;
    error_page 401 /error/401.html;
    error_page 403 /error/403.html;
    error_page 404 /error/404.html;
    error_page 405 /error/405.html;
    error_page 500 /error/500.html;
    error_page 501 /error/501.html;
    error_page 502 /error/502.html;
    error_page 503 /error/503.html;

    location / {
        autoindex on;
        can_upload on;

        alias /www;
        return /www;

        upload_path /www/upload;

        index index.html index.htm index.php;

        cgi_extensions .php .py;

        allow_methods GET POST DELETE;
    }
}

# -------- SERVER 2 --------
# Secondary server for tests / API
server {

    server_name localhost;

    listen 127.0.0.1:8081;

    client_max_body_size 5M;

    root ./;

    location / {
        autoindex off;

        alias /www/test;
        return /www/test;

        index test.html;

        allow_methods GET;
    }
}
